version: '3'

services:
 # web:
 #   image: nginx
 #   ports:
 #     - "80:80"
 #   volumes:
 #     - ./nginx.conf:/etc/nginx/nginx.conf
 #   depends_on:
 #     - app
  app:
    build: .
    volumes:
      - .:/app
    ports:
      - "3001:3001"
    environment:
      - RAILS_ENV=development
      - RACK_ENV=development
      - PORT=3001
    working_dir: /app
    